# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json
# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
vacation_df = pd.read_csv("vacation.csv")
vacation_df.head()

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Latitude,Longitude,Max Temp,Wind Speed
0,0,mataura,99.0,NZ,2019-09-29 19:13:21,90.0,-46.19,168.86,45.00,4.00
1,1,yar-sale,99.0,RU,2019-09-29 19:13:22,77.0,66.83,70.83,32.09,10.92
2,2,bitung,20.0,ID,2019-09-29 19:13:22,88.0,1.44,125.19,75.20,1.12
3,3,mahibadhoo,100.0,MV,2019-09-29 19:13:22,72.0,3.78,72.97,82.13,11.23
4,4,cape town,20.0,ZA,2019-09-29 19:13:22,72.0,-33.93,18.42,60.01,13.87

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [6]:

# Configure gmaps with API key
gmaps.configure(api_key=g_key)

In [7]:

# Store latitude and longitude in locations
locations = vacation_df[["Latitude", "Longitude"]]
vacation_df.replace("", np.nan, inplace = True)
vacation_df = vacation_df.dropna()

# Fill NaN values and convert to float
humidity = vacation_df["Humidity"].astype(float)

In [8]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [9]:
vacation_df["Hotel Name"] = ""
vac_file=vacation_df.loc[(vacation_df['Max Temp']>=70)&(vacation_df['Max Temp']<=80)]
wind_file=vac_file.loc[(vac_file['Wind Speed']<=10)]
file=wind_file.loc[(wind_file['Cloudiness']==0)]
file.head()

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Latitude,Longitude,Max Temp,Wind Speed,Hotel Name
41,41,saldanha,0.0,PT,2019-09-29 19:13:28,49.0,41.42,-6.55,72.59,7.43,
73,73,maoming,0.0,CN,2019-09-29 19:13:32,68.0,21.67,110.92,74.39,4.00,
89,89,noumea,0.0,NC,2019-09-29 19:10:33,93.0,-22.28,166.46,73.00,5.79,
103,103,chara,0.0,GR,2019-09-29 19:13:37,68.0,39.42,22.43,71.60,4.50,
162,162,blagnac,0.0,FR,2019-09-29 19:13:45,33.0,43.64,1.38,77.00,9.17,

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [10]:
hotel_df = file.reset_index(drop=True)
hotel_df
hotel_df["Hotel Name"] = ""
hotel_df
#hotel_df = hotel_df.loc[:, ~hotel.columns.str.contains()]
hotel_df

params = {
  "radius": 5000,
  "types": "hotel",
  "keyword": "hotels",
  "key": g_key
}
for index, row in hotel_df.iterrows():
    lat = row["Latitude"]
    lon = row["Longitude"]
    params["location"] = f"{lat},{lon}"
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    name_address = requests.get(base_url, params=params)
    name_address = name_address.json()
    
    try:
        hotel_df.loc[index, "Hotel Name"] = name_address["results"][0]["name"]
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.

In [16]:
# Save Data to csv
hotel_df.to_csv("Hotels_Output.csv")
# Visualize to confirm data appears
hotel_df.head()

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Latitude,Longitude,Max Temp,Wind Speed,Hotel Name
0,41,saldanha,0.0,PT,2019-09-29 19:13:28,49.0,41.42,-6.55,72.59,7.43,
1,73,maoming,0.0,CN,2019-09-29 19:13:32,68.0,21.67,110.92,74.39,4.00,Wyndham Maoming
2,89,noumea,0.0,NC,2019-09-29 19:10:33,93.0,-22.28,166.46,73.00,5.79,Hotel Beaurivage
3,103,chara,0.0,GR,2019-09-29 19:13:37,68.0,39.42,22.43,71.60,4.50,
4,162,blagnac,0.0,FR,2019-09-29 19:13:45,33.0,43.64,1.38,77.00,9.17,Hotel Mercure Toulouse Aéroport Golf de Seilh

In [18]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Latitude", "Longitude"]]

In [19]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, hotel_info)

# Add the layer to the map

fig.add_layer(markers)

# Display Map
fig

Figure(layout=FigureLayout(height='420px'))